on:
  push:
    paths:
      - '**/README.Rmd'
      - 'examples/*yaml'
      - 'DESCRIPTION'
      - 'NEWS.md'
  workflow_dispatch:

name: Render README

permissions:
  contents: write

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages(c("devtools", "badger"))
          devtools::install_local(".", dependencies = TRUE)
          devtools::install_cran("rmarkdown")
        shell: Rscript {0}
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Render helpfiles
        run: Rscript -e 'devtools::document()'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git commit man/* -m 'Re-build helpfiles' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - name: Install pkgdown
        run: Rscript -e 'install.packages("pkgdown", type = "binary")'
      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
